global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Scrape metrics from monitor service
  - job_name: 'envoy-monitor'
    static_configs:
      - targets: ['monitor:8000']
        labels:
          service: 'monitor'
